[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "check-json" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending" },
  { id = "check-added-large-files" },
  { id = "check-executables-have-shebangs" },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-vcs-permalinks" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-illegal-windows-names" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
  { id = "actionlint" }
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.24.0"
hooks = [
  { id = "gitleaks" }
]
[[repos]]
repo = "https://github.com/Yelp/detect-secrets"
rev = "v1.5.0"
hooks = [
  { id = "detect-secrets" }
]
